global:
  imagePullPolicy: Always
  ###vault:
  ###  host: ip
  ###  name: vault
  ###  vaultToken: someToken


frontend:
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  service:
    port: 80
  ingress:
    host: front-alexandervasiliev-x23.2sem.students-projects.ru
    path: /
    pathType: Prefix
  containerPort: 80
  image: alexanderx23/sausage-frontend:latest
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "1"
  nginxConf: nginx.conf

backend:
  annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
  env:
    postgresUri: jdbc:postgresql://postgresql:5432/sausage-store
    postgresUser: store
    postgresPassword: storepassword
    mongodbUri: "mongodb://reports:reportspassword@mongodb:27017/sausage-store?authSource=sausage-store"
    reportPath: /logs/reports
    logPath: /logs
  service:
    port: 8080
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
    type: RollingUpdate
  image: alexanderx23/sausage-backend:latest
  imagePullPolicy: Always
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "1"
  containerPort: 8080
  livenessProbe:
    httpGet:
      path: "/actuator/health"
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 10
  vpa:
    updatePolicy:
      updateMode: "Recreate"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: "50m"
            memory: "64Mi"
          maxAllowed:
            cpu: "500m"
            memory: "1Gi"
          controlledResources: [ "cpu", "memory" ]

backend-report:
  replicaCount: 1
  strategy:
    type: Recreate
  image:
    repository: alexanderx23/sausage-backend-report
    tag: latest
  #  mongoConnectionString: "mongodb://reports:reportspassword@mongodb:27017/sausage-store?authSource=sausage-store"
  base64MongoConnectionString: "bW9uZ29kYjovL3JlcG9ydHM6cmVwb3J0c3Bhc3N3b3JkQG1vbmdvZGI6MjcwMTcvc2F1c2FnZS1zdG9yZT9hdXRoU291cmNlPXNhdXNhZ2Utc3RvcmU="
  port: "8080"
  containerPort: 8080
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "100m"
  hpa:
    minReplicas: 1
    maxReplicas: 5
    cpuUtilizationPercentage: 30

infra:
  postgresql:
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "100m"
    env:
      POSTGRES_PASSWORD: storepassword
      POSTGRES_USER: store
      POSTGRES_DB: sausage-store
    containerPort: 5432
  mongodb:
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "100m"
    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    containerPort: 27017
